In [54]:
import pandas as pd
import numpy as np

In [55]:
df = pd.read_csv("full_data.csv")
df.head()

,vacancy_id,vacancy_url,name,description_clean,snippet_requirement,snippet_responsibility,key_skills,professional_roles,area_name,experience_name,schedule_name,employment_name,work_format,internship,salary_from,salary_to,salary_currency,salary_gross,employer_name,published_at
0,131765894,https://hh.ru/vacancy/131765894,ML-инженер / Machine Learning Engineer,Международная компания MINISO Kazakhstan пригл...,NaN,NaN,MLflow | ERP | Docker | API | Python,Дата-сайентист,Алматы,От 3 до 6 лет,Полный день,Полная занятость,На месте работодателя,False,1200000.0,NaN,KZT,False,MINISO Kazakhstan,2026-04-02T08:55:12+0300
1,130285387,https://hh.ru/vacancy/130285387,Инженер компьютерного зрения / Machine Learnin...,Межрегиональная группа компаний «ИНТЕХРОС» раб...,NaN,NaN,Python | YOLO | GitHub | OpenCV | Nvidia Jetso...,"Программист, разработчик",Воронеж,От 1 года до 3 лет,Полный день,Полная занятость,На месте работодателя,False,150000.0,NaN,RUR,True,"ИНТЕХРОС, Межрегиональная группа компаний",2026-04-01T07:41:53+0300
2,128539097,https://hh.ru/vacancy/128539097,"Machine Learning Engineer (RecSys, E-com)","Мы ищем опытного ML Engineer , который присоед...",NaN,NaN,NaN,Дата-сайентист,Москва,От 1 года до 3 лет,Удаленная работа,Полная занятость,Удалённо | Гибрид,False,NaN,NaN,NaN,NaN,GRI,2026-03-30T10:39:14+0300
3,131619736,https://hh.ru/vacancy/131619736,AI / Machine Learning Engineer,Обязанности: •Ведение и координация проектов в...,NaN,NaN,Python | Английский язык | MySQL | MS SQL Serv...,Дата-сайентист,Ташкент,От 3 до 6 лет,Полный день,Полная занятость,На месте работодателя,False,15000000.0,15000000.0,UZS,False,Safia кондитерский дом,2026-03-27T15:42:27+0300
4,131478467,https://hh.ru/vacancy/131478467,Robotics Software Engineer,ТехВилл – IT-компания и партнёр ВкусВилл по р...,NaN,NaN,NaN,"Программист, разработчик",Москва,От 1 года до 3 лет,Полный день,Полная занятость,Гибрид,False,NaN,NaN,NaN,NaN,ТехВилл,2026-04-01T16:30:37+0300

In [56]:
df.columns

Index(['vacancy_id', 'vacancy_url', 'name', 'description_clean',
       'snippet_requirement', 'snippet_responsibility', 'key_skills',
       'professional_roles', 'area_name', 'experience_name', 'schedule_name',
       'employment_name', 'work_format', 'internship', 'salary_from',
       'salary_to', 'salary_currency', 'salary_gross', 'employer_name',
       'published_at'],
      dtype='str')

In [57]:
df.dtypes

vacancy_id                  int64
vacancy_url                   str
name                          str
description_clean             str
snippet_requirement       float64
snippet_responsibility    float64
key_skills                    str
professional_roles            str
area_name                     str
experience_name               str
schedule_name                 str
employment_name               str
work_format                   str
internship                   bool
salary_from               float64
salary_to                 float64
salary_currency               str
salary_gross               object
employer_name                 str
published_at                  str
dtype: object

In [59]:
for i in np.unique(df["professional_roles"]):
    print(i)

BI-аналитик, аналитик данных
DevOps-инженер
Event-менеджер
PR-менеджер
SMM-менеджер, контент-менеджер
Автослесарь, автомеханик
Агент по недвижимости
Администратор
Аналитик
Андеррайтер
Арт-директор, креативный директор
Архитектор
Аудитор
Бизнес-аналитик
Бизнес-тренер
Бухгалтер
Видеооператор, видеомонтажер
Водитель
Гейм-дизайнер
Геолог
Главный инженер проекта
Дата-сайентист
Делопроизводитель, архивариус
Дизайнер, художник
Директор по информационным технологиям (CIO)
Директор по маркетингу и PR (CMO)
Директор по персоналу (HRD)
Другое
Инженер ПНР
Инженер ПТО, инженер-сметчик
Инженер по качеству
Инженер по охране труда и технике безопасности, инженер-эколог
Инженер по эксплуатации
Инженер-конструктор, инженер-проектировщик
Инженер-электроник, инженер-электронщик
Инженер-энергетик, инженер-электрик
Казначей
Коммерческий директор (CCO)
Комплаенс-менеджер
Координатор отдела продаж
Копирайтер, редактор, корректор
Кредитный специалист
Менеджер по компенсациям и льготам
Менеджер по логистике, менеджер по ВЭД
Менеджер по маркетингу, интернет-маркетолог
Менеджер по персоналу
Менеджер по продажам, менеджер по работе с клиентами
Менеджер по работе с партнерами
Менеджер продукта
Менеджер/консультант по стратегии
Методист
Методолог
Метролог
Механик
Научный специалист, исследователь
Начальник склада
Оператор ПК, оператор базы данных
Операционный директор (COO)
Офис-менеджер
Повар, пекарь, кондитер
Программист, разработчик
Продуктовый аналитик
Продюсер
Психолог
Руководитель группы разработки
Руководитель отдела аналитики
Руководитель отдела клиентского обслуживания
Руководитель отдела маркетинга и рекламы
Руководитель отдела продаж
Руководитель проектов
Руководитель строительного проекта
Сварщик
Секретарь, помощник руководителя, ассистент
Сервисный инженер, инженер-механик
Сетевой инженер
Системный администратор
Системный аналитик
Системный инженер
Слесарь, сантехник
Специалист по информационной безопасности
Специалист по кадрам
Специалист по подбору персонала
Специалист службы безопасности
Специалист технической поддержки
Тестировщик
Технический директор (CTO)
Технический писатель
Технолог
Упаковщик, комплектовщик
Учитель, преподаватель, педагог
Финансовый аналитик, инвестиционный аналитик
Финансовый директор (CFO)
Финансовый контролер
Финансовый менеджер
Швея, портной, закройщик
Экономист
Юрисконсульт
Юрист

In [60]:
roles = [
    "BI-аналитик, аналитик данных",
    "DevOps-инженер",
    "Бизнес-аналитик",
    "Дата-сайентист",
    "Программист, разработчик",
    "Продуктовый аналитик",
    "Системный аналитик",
    "Системный инженер",
    "Тестировщик",
]

In [61]:
df_relevant = df[df["professional_roles"].isin(roles)]
df_relevant.info()

<class 'pandas.DataFrame'>
Index: 1290 entries, 0 to 2273
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   vacancy_id              1290 non-null   int64
 1   vacancy_url             1290 non-null   str
 2   name                    1290 non-null   str
 3   description_clean       1290 non-null   str
 4   snippet_requirement     0 non-null      float64
 5   snippet_responsibility  0 non-null      float64
 6   key_skills              819 non-null    str
 7   professional_roles      1290 non-null   str
 8   area_name               1290 non-null   str
 9   experience_name         1290 non-null   str
 10  schedule_name           1290 non-null   str
 11  employment_name         1290 non-null   str
 12  work_format             1214 non-null   str
 13  internship              1290 non-null   bool
 14  salary_from             290 non-null    float64
 15  salary_to               203 non-null    float64
 16  salary_currency         333 non-null    str
 17  salary_gross            333 non-null    object
 18  employer_name           1290 non-null   str
 19  published_at            1290 non-null   str
dtypes: bool(1), float64(4), int64(1), object(1), str(13)
memory usage: 202.8+ KB

In [62]:
df_relevant.head()

,vacancy_id,vacancy_url,name,description_clean,snippet_requirement,snippet_responsibility,key_skills,professional_roles,area_name,experience_name,schedule_name,employment_name,work_format,internship,salary_from,salary_to,salary_currency,salary_gross,employer_name,published_at
0,131765894,https://hh.ru/vacancy/131765894,ML-инженер / Machine Learning Engineer,Международная компания MINISO Kazakhstan пригл...,NaN,NaN,MLflow | ERP | Docker | API | Python,Дата-сайентист,Алматы,От 3 до 6 лет,Полный день,Полная занятость,На месте работодателя,False,1200000.0,NaN,KZT,False,MINISO Kazakhstan,2026-04-02T08:55:12+0300
1,130285387,https://hh.ru/vacancy/130285387,Инженер компьютерного зрения / Machine Learnin...,Межрегиональная группа компаний «ИНТЕХРОС» раб...,NaN,NaN,Python | YOLO | GitHub | OpenCV | Nvidia Jetso...,"Программист, разработчик",Воронеж,От 1 года до 3 лет,Полный день,Полная занятость,На месте работодателя,False,150000.0,NaN,RUR,True,"ИНТЕХРОС, Межрегиональная группа компаний",2026-04-01T07:41:53+0300
2,128539097,https://hh.ru/vacancy/128539097,"Machine Learning Engineer (RecSys, E-com)","Мы ищем опытного ML Engineer , который присоед...",NaN,NaN,NaN,Дата-сайентист,Москва,От 1 года до 3 лет,Удаленная работа,Полная занятость,Удалённо | Гибрид,False,NaN,NaN,NaN,NaN,GRI,2026-03-30T10:39:14+0300
3,131619736,https://hh.ru/vacancy/131619736,AI / Machine Learning Engineer,Обязанности: •Ведение и координация проектов в...,NaN,NaN,Python | Английский язык | MySQL | MS SQL Serv...,Дата-сайентист,Ташкент,От 3 до 6 лет,Полный день,Полная занятость,На месте работодателя,False,15000000.0,15000000.0,UZS,False,Safia кондитерский дом,2026-03-27T15:42:27+0300
4,131478467,https://hh.ru/vacancy/131478467,Robotics Software Engineer,ТехВилл – IT-компания и партнёр ВкусВилл по р...,NaN,NaN,NaN,"Программист, разработчик",Москва,От 1 года до 3 лет,Полный день,Полная занятость,Гибрид,False,NaN,NaN,NaN,NaN,ТехВилл,2026-04-01T16:30:37+0300

In [63]:
df_relevant.to_csv("relevant_data.csv", index=False)

In [41]:
np.unique(df_relevant["professional_roles"], return_counts=True)

(array(['BI-аналитик, аналитик данных', 'DevOps-инженер',
        'Бизнес-аналитик', 'Дата-сайентист', 'Программист, разработчик',
        'Продуктовый аналитик', 'Системный аналитик', 'Системный инженер',
        'Тестировщик'], dtype=object),
 array([ 99,  86,  37, 403, 560,  13,  29,  17,  46]))

In [45]:
df_relevant.drop(columns=["snippet_requirement", "snippet_responsibility"], inplace=True)

In [46]:
df_relevant.info()

<class 'pandas.DataFrame'>
Index: 1290 entries, 0 to 2273
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   vacancy_id          1290 non-null   int64
 1   vacancy_url         1290 non-null   str
 2   name                1290 non-null   str
 3   description_clean   1290 non-null   str
 4   key_skills          819 non-null    str
 5   professional_roles  1290 non-null   str
 6   area_name           1290 non-null   str
 7   experience_name     1290 non-null   str
 8   schedule_name       1290 non-null   str
 9   employment_name     1290 non-null   str
 10  work_format         1214 non-null   str
 11  internship          1290 non-null   bool
 12  salary_from         290 non-null    float64
 13  salary_to           203 non-null    float64
 14  salary_currency     333 non-null    str
 15  salary_gross        333 non-null    object
 16  employer_name       1290 non-null   str
 17  published_at        1290 non-null   str
dtypes: bool(1), float64(2), int64(1), object(1), str(13)
memory usage: 182.7+ KB

# Catboost

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

from catboost import CatBoostRegressor, Pool

# =========================================================
# 1. Исходный DataFrame
# =========================================================
# Предполагается, что DataFrame уже загружен и называется df
# Например:s
df = pd.read_csv("relevant_data.csv")

df = df.copy()

In [2]:
all_competences = list()
for competence_list in np.unique(df["key_skills"].apply(str)):
    for competence in competence_list.split(" | "):
        all_competences.append(competence.strip("• "))

print(np.unique(all_competences, return_counts=True))

(array(['.NET', '.NET 6+', '.NET Core', ..., 'распознование целей',
       'система управления полётом', 'фрод - мониторинг'],
      shape=(1103,), dtype='<U77'), array([1, 2, 3, ..., 1, 1, 1], shape=(1103,)))

In [3]:
from collections import Counter

top_30 = Counter(all_competences).most_common(30)

print(top_30)

[('Python', 410), ('SQL', 189), ('Docker', 128), ('PostgreSQL', 108), ('PyTorch', 101), ('Linux', 97), ('LLM', 82), ('Kubernetes', 79), ('Git', 77), ('ML', 59), ('FastAPI', 59), ('MLflow', 53), ('TensorFlow', 46), ('CI/CD', 42), ('Английский язык', 38), ('Big Data', 38), ('Apache Airflow', 37), ('pandas', 37), ('REST API', 36), ('NLP', 36), ('Машинное обучение', 33), ('Apache Kafka', 32), ('Deep Learning', 31), ('Grafana', 31), ('Clickhouse', 31), ('AI', 30), ('Анализ данных', 30), ('Redis', 30), ('Numpy', 30), ('API', 28)]

In [4]:
df["key_skills"] = df["key_skills"].apply(str)

In [5]:
for skill, _ in top_30:
    df[f"skill_{skill}"] = df["key_skills"].apply(lambda x: 1 if x.count(skill) else 0)

In [6]:
df

,vacancy_id,vacancy_url,name,description_clean,snippet_requirement,snippet_responsibility,key_skills,professional_roles,area_name,experience_name,...,skill_Машинное обучение,skill_Apache Kafka,skill_Deep Learning,skill_Grafana,skill_Clickhouse,skill_AI,skill_Анализ данных,skill_Redis,skill_Numpy,skill_API
0,131765894,https://hh.ru/vacancy/131765894,ML-инженер / Machine Learning Engineer,Международная компания MINISO Kazakhstan пригл...,NaN,NaN,MLflow | ERP | Docker | API | Python,Дата-сайентист,Алматы,От 3 до 6 лет,...,0,0,0,0,0,0,0,0,0,1
1,130285387,https://hh.ru/vacancy/130285387,Инженер компьютерного зрения / Machine Learnin...,Межрегиональная группа компаний «ИНТЕХРОС» раб...,NaN,NaN,Python | YOLO | GitHub | OpenCV | Nvidia Jetso...,"Программист, разработчик",Воронеж,От 1 года до 3 лет,...,0,0,0,0,0,0,0,0,0,0
2,128539097,https://hh.ru/vacancy/128539097,"Machine Learning Engineer (RecSys, E-com)","Мы ищем опытного ML Engineer , который присоед...",NaN,NaN,nan,Дата-сайентист,Москва,От 1 года до 3 лет,...,0,0,0,0,0,0,0,0,0,0
3,131619736,https://hh.ru/vacancy/131619736,AI / Machine Learning Engineer,Обязанности: •Ведение и координация проектов в...,NaN,NaN,Python | Английский язык | MySQL | MS SQL Serv...,Дата-сайентист,Ташкент,От 3 до 6 лет,...,0,0,1,0,0,0,0,0,0,0
4,131478467,https://hh.ru/vacancy/131478467,Robotics Software Engineer,ТехВилл – IT-компания и партнёр ВкусВилл по р...,NaN,NaN,nan,"Программист, разработчик",Москва,От 1 года до 3 лет,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1285,130631675,https://hh.ru/vacancy/130631675,Middle DataScientist,"Halyk Банк – это мощная экосистема, где технол...",NaN,NaN,SQL | Python | Qlik Sense | Машинное обучение,Дата-сайентист,Алматы,От 3 до 6 лет,...,1,0,0,0,0,0,0,0,0,0
1286,130891219,https://hh.ru/vacancy/130891219,Бизнес-аналитик (медтех),"Команда Technology - одно из самых молодых, ра...",NaN,NaN,MS PowerPoint | Бизнес-анализ | MS Excel,Бизнес-аналитик,Москва,От 1 года до 3 лет,...,0,0,0,0,0,0,0,0,0,0
1287,131126104,https://hh.ru/vacancy/131126104,Исследователь больших данных/ Middle+ MLE (GeoML),Лента — федеральный продуктовый ритейлер Росси...,NaN,NaN,nan,Дата-сайентист,Москва,От 3 до 6 лет,...,0,0,0,0,0,0,0,0,0,0
1288,131115534,https://hh.ru/vacancy/131115534,Аналитик-исследователь,Обязанности: Анализ рабочих процессов и данных...,NaN,NaN,nan,Системный аналитик,Москва,От 1 года до 3 лет,...,0,0,0,0,0,0,0,0,0,0
1289,129945040,https://hh.ru/vacancy/129945040,Старший продуктовый аналитик в Дзен,Мы создаём самую большую рекомендательную сист...,NaN,NaN,nan,Продуктовый аналитик,Москва,От 3 до 6 лет,...,0,0,0,0,0,0,0,0,0,0

In [7]:
# =========================================================
# 2. Сбор целевой переменной
# =========================================================
def build_target_salary(row):
    s_from = row["salary_from"]
    s_to = row["salary_to"]

    if pd.notna(s_from) and pd.notna(s_to):
        return (s_from + s_to) / 2.0
    elif pd.notna(s_from):
        return s_from
    elif pd.notna(s_to):
        return s_to
    else:
        return np.nan

df["target_salary_raw"] = df.apply(build_target_salary, axis=1)

In [9]:
# =========================================================
# 3. Приведение валют к RUB
# =========================================================

import requests

def get_currency_rates_to_rub():
    fallback = {
        "RUR": 1.0,
        "USD": 79.7293,
        "EUR": 92.1915,
        "KZT": 0.168807,
        "BYR": 27.1521,
        "UZS": 0.00655094,
        "KGS": 0.911713,
    }

    # try:
    #     url = "https://www.cbr-xml-daily.ru/daily_json.js"
    #     data = requests.get(url, timeout=10)
    #     data.raise_for_status()
    #     data = data.json()

    #     rates = {
    #         "RUR": 1.0,
    #     }

    #     for code, item in data["Valute"].items():
    #         rates[code] = item["Value"] / item["Nominal"]

    #     if "BYN" in rates:
    #         rates["BYR"] = rates["BYN"]

    #     return rates

    # except Exception:
    return fallback


def convert_to_rub(row):
    currency_rates = get_currency_rates_to_rub()

    salary = row["target_salary_raw"]
    currency = row["salary_currency"]

    if pd.isna(salary):
        return np.nan

    if pd.isna(currency):
        currency = "RUR"

    rate = currency_rates.get(currency)
    if rate is None:
        return np.nan

    return salary * rate

df["target_salary"] = df.apply(convert_to_rub, axis=1)

In [10]:
# =========================================================
# 4. Подготовка признаков
# =========================================================
text_cols = ["name", "description_clean", "key_skills"]

for col in text_cols:
    df[col] = df[col].fillna("").astype(str)

cat_cols = [
    "professional_roles",
    "area_name",
    "experience_name",
    "schedule_name",
    "employment_name",
    "work_format",
    "employer_name",
]

for col in cat_cols:
    df[col] = df[col].fillna("UNKNOWN").astype(str)

df["internship"] = df["internship"].astype(int)

df["published_at"] = pd.to_datetime(df["published_at"], errors="coerce")
df["pub_year"] = df["published_at"].dt.year.fillna(0).astype(int)
df["pub_month"] = df["published_at"].dt.month.fillna(0).astype(int)
df["pub_weekday"] = df["published_at"].dt.weekday.fillna(0).astype(int)

# # Можно сделать общий текст, но для CatBoost лучше оставить отдельные текстовые колонки
# df["full_text"] = (
#     df["name"] + " [SEP] " +
#     df["description_clean"] + " [SEP] " +
#     df["key_skills"]
# )

In [12]:
# =========================================================
# 5. Датасет для обучения
# =========================================================
train_df = df[df["target_salary"].notna()].copy()

# Фильтрация явных выбросов — очень желательна
train_df = train_df[
    (train_df["target_salary"] >= 20000) &
    (train_df["target_salary"] <= 1000000)
].copy()

train_df["target_log"] = np.log1p(train_df["target_salary"])

print("Строк с известной зарплатой:", len(train_df))

Строк с известной зарплатой: 330

In [32]:
train_df.drop(columns=["snippet_requirement", "snippet_responsibility"], inplace=True)
train_df.to_csv("train_data.csv", index=False)

In [33]:
# =========================================================
# 6. Признаки для модели
# =========================================================
feature_cols = [
    "name",
    # "description_clean",
    # "key_skills",
    "professional_roles",
    "area_name",
    "experience_name",
    "schedule_name",
    "employment_name",
    "work_format",
    # "employer_name",
    "internship",
    # "pub_year",
    # "pub_month",
    # "pub_weekday",
]

for col in train_df.columns:
    if col.startswith("skill_"):
        feature_cols.append(col)

text_features = ["name"]
cat_features = [
    "professional_roles",
    "area_name",
    "experience_name",
    "schedule_name",
    "employment_name",
    "work_format",
    # "employer_name",
]
# num_features = ["internship", "pub_year", "pub_month", "pub_weekday"]

X = train_df[feature_cols].copy()
y = train_df["target_log"].copy()

In [34]:
# =========================================================
# 7. Train / Valid split
# =========================================================
X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Индексы признаков для CatBoost
cat_feature_indices = [X_train.columns.get_loc(col) for col in cat_features]
text_feature_indices = [X_train.columns.get_loc(col) for col in text_features]

train_pool = Pool(
    data=X_train,
    label=y_train,
    cat_features=cat_feature_indices,
    text_features=text_feature_indices,
)

valid_pool = Pool(
    data=X_valid,
    label=y_valid,
    cat_features=cat_feature_indices,
    text_features=text_feature_indices,
)

In [35]:
from catboost import CatBoostRegressor
from sklearn.model_selection import GridSearchCV

base_model = CatBoostRegressor(
    loss_function="RMSE",
    eval_metric="MAE",
    od_type="Iter",
    od_wait=100,
    random_seed=42,
    verbose=0
)

param_grid = {
    "depth": [4, 6, 8],
    "learning_rate": [0.03, 0.05, 0.1],
    "l2_leaf_reg": [3, 5, 7],
    "iterations": [500, 1000]
}

grid = GridSearchCV(
    estimator=base_model,
    param_grid=param_grid,
    scoring="neg_mean_absolute_error",
    cv=3,
    n_jobs=-1,
    verbose=2
)

grid.fit(
    X_train,
    y_train,
    cat_features=cat_feature_indices,
    text_features=text_feature_indices
)

print("Лучшие параметры:", grid.best_params_)
print("Лучший CV score:", -grid.best_score_)

Fitting 3 folds for each of 54 candidates, totalling 162 fits
[CV] END depth=4, iterations=500, l2_leaf_reg=3, learning_rate=0.03; total time=   2.7s
[CV] END depth=4, iterations=500, l2_leaf_reg=3, learning_rate=0.03; total time=   3.9s
[CV] END depth=4, iterations=500, l2_leaf_reg=3, learning_rate=0.03; total time=   3.6s
[CV] END depth=4, iterations=500, l2_leaf_reg=3, learning_rate=0.05; total time=   3.9s
[CV] END depth=4, iterations=500, l2_leaf_reg=3, learning_rate=0.05; total time=   2.6s
[CV] END depth=4, iterations=500, l2_leaf_reg=3, learning_rate=0.1; total time=   2.3s
[CV] END depth=4, iterations=500, l2_leaf_reg=3, learning_rate=0.05; total time=   2.7s
[CV] END depth=4, iterations=500, l2_leaf_reg=3, learning_rate=0.1; total time=   2.9s
[CV] END depth=4, iterations=500, l2_leaf_reg=3, learning_rate=0.1; total time=   3.3s
[CV] END depth=4, iterations=500, l2_leaf_reg=5, learning_rate=0.03; total time=   2.6s
[CV] END depth=4, iterations=500, l2_leaf_reg=5, learning_rate=0.03; total time=   2.5s
[CV] END depth=4, iterations=500, l2_leaf_reg=5, learning_rate=0.03; total time=   3.8s
[CV] END depth=4, iterations=500, l2_leaf_reg=5, learning_rate=0.1; total time=   2.3s
[CV] END depth=4, iterations=500, l2_leaf_reg=5, learning_rate=0.05; total time=   3.2s
[CV] END depth=4, iterations=500, l2_leaf_reg=5, learning_rate=0.05; total time=   3.5s
[CV] END depth=4, iterations=500, l2_leaf_reg=5, learning_rate=0.05; total time=   3.2s
[CV] END depth=4, iterations=500, l2_leaf_reg=5, learning_rate=0.1; total time=   3.0s
[CV] END depth=4, iterations=500, l2_leaf_reg=7, learning_rate=0.03; total time=   2.9s
[CV] END depth=4, iterations=500, l2_leaf_reg=5, learning_rate=0.1; total time=   3.6s
[CV] END depth=4, iterations=500, l2_leaf_reg=7, learning_rate=0.03; total time=   3.4s
[CV] END depth=4, iterations=500, l2_leaf_reg=7, learning_rate=0.05; total time=   2.8s
[CV] END depth=4, iterations=500, l2_leaf_reg=7, learning_rate=0.03; total time=   3.4s
[CV] END depth=4, iterations=500, l2_leaf_reg=7, learning_rate=0.05; total time=   2.9s
[CV] END depth=4, iterations=500, l2_leaf_reg=7, learning_rate=0.05; total time=   3.4s
[CV] END depth=4, iterations=500, l2_leaf_reg=7, learning_rate=0.1; total time=   2.4s
[CV] END depth=4, iterations=500, l2_leaf_reg=7, learning_rate=0.1; total time=   2.3s
[CV] END depth=4, iterations=500, l2_leaf_reg=7, learning_rate=0.1; total time=   3.7s
[CV] END depth=4, iterations=1000, l2_leaf_reg=3, learning_rate=0.03; total time=   5.5s
[CV] END depth=4, iterations=1000, l2_leaf_reg=3, learning_rate=0.03; total time=   6.0s
[CV] END depth=4, iterations=1000, l2_leaf_reg=3, learning_rate=0.05; total time=   5.3s
[CV] END depth=4, iterations=1000, l2_leaf_reg=3, learning_rate=0.03; total time=   6.5s
[CV] END depth=4, iterations=1000, l2_leaf_reg=3, learning_rate=0.05; total time=   5.8s
[CV] END depth=4, iterations=1000, l2_leaf_reg=3, learning_rate=0.05; total time=   5.6s
[CV] END depth=4, iterations=1000, l2_leaf_reg=3, learning_rate=0.1; total time=   5.5s
[CV] END depth=4, iterations=1000, l2_leaf_reg=3, learning_rate=0.1; total time=   6.7s
[CV] END depth=4, iterations=1000, l2_leaf_reg=3, learning_rate=0.1; total time=   5.1s
[CV] END depth=4, iterations=1000, l2_leaf_reg=5, learning_rate=0.03; total time=   5.2s
[CV] END depth=4, iterations=1000, l2_leaf_reg=5, learning_rate=0.03; total time=   4.8s
[CV] END depth=4, iterations=1000, l2_leaf_reg=5, learning_rate=0.03; total time=   5.1s
[CV] END depth=4, iterations=1000, l2_leaf_reg=5, learning_rate=0.05; total time=   4.2s
[CV] END depth=4, iterations=1000, l2_leaf_reg=5, learning_rate=0.05; total time=   6.9s
[CV] END depth=4, iterations=1000, l2_leaf_reg=5, learning_rate=0.05; total time=   5.3s
[CV] END depth=4, iterations=1000, l2_leaf_reg=5, learning_rate=0.1; total time=   6.2s
[CV] END depth=4, iterations=1000, l2_leaf_reg=5, learning_rate=0.1; total time=   5.3s
[CV] END depth=4, iterations=1000, l2_leaf_reg=7, learning_rate=0.03; total time=   5.3s
[CV] END depth=4, iterations=1000, l2_leaf_reg=5, learning_rate=0.1; total time=   6.5s
[CV] END depth=4, iterations=1000, l2_leaf_reg=7, learning_rate=0.03; total time=   6.4s
[CV] END depth=4, iterations=1000, l2_leaf_reg=7, learning_rate=0.03; total time=   5.1s
[CV] END depth=4, iterations=1000, l2_leaf_reg=7, learning_rate=0.05; total time=   5.3s
[CV] END depth=4, iterations=1000, l2_leaf_reg=7, learning_rate=0.05; total time=   6.5s
[CV] END depth=4, iterations=1000, l2_leaf_reg=7, learning_rate=0.05; total time=   5.0s
[CV] END depth=4, iterations=1000, l2_leaf_reg=7, learning_rate=0.1; total time=   5.3s
[CV] END depth=4, iterations=1000, l2_leaf_reg=7, learning_rate=0.1; total time=   5.4s
[CV] END depth=4, iterations=1000, l2_leaf_reg=7, learning_rate=0.1; total time=   5.8s
[CV] END depth=6, iterations=500, l2_leaf_reg=3, learning_rate=0.03; total time=   7.9s
[CV] END depth=6, iterations=500, l2_leaf_reg=3, learning_rate=0.03; total time=   8.6s
[CV] END depth=6, iterations=500, l2_leaf_reg=3, learning_rate=0.03; total time=   9.9s
[CV] END depth=6, iterations=500, l2_leaf_reg=3, learning_rate=0.05; total time=   9.7s
[CV] END depth=6, iterations=500, l2_leaf_reg=3, learning_rate=0.05; total time=   7.9s
[CV] END depth=6, iterations=500, l2_leaf_reg=3, learning_rate=0.05; total time=   8.9s
[CV] END depth=6, iterations=500, l2_leaf_reg=3, learning_rate=0.1; total time=   9.0s
[CV] END depth=6, iterations=500, l2_leaf_reg=3, learning_rate=0.1; total time=   7.8s
[CV] END depth=6, iterations=500, l2_leaf_reg=3, learning_rate=0.1; total time=   8.2s
[CV] END depth=6, iterations=500, l2_leaf_reg=5, learning_rate=0.03; total time=   6.8s
[CV] END depth=6, iterations=500, l2_leaf_reg=5, learning_rate=0.03; total time=   8.0s
[CV] END depth=6, iterations=500, l2_leaf_reg=5, learning_rate=0.03; total time=   9.2s
[CV] END depth=6, iterations=500, l2_leaf_reg=5, learning_rate=0.05; total time=   9.3s
[CV] END depth=6, iterations=500, l2_leaf_reg=5, learning_rate=0.05; total time=   7.4s
[CV] END depth=6, iterations=500, l2_leaf_reg=5, learning_rate=0.05; total time=   7.2s
[CV] END depth=6, iterations=500, l2_leaf_reg=5, learning_rate=0.1; total time=   9.6s
[CV] END depth=6, iterations=500, l2_leaf_reg=5, learning_rate=0.1; total time=   7.8s
[CV] END depth=6, iterations=500, l2_leaf_reg=5, learning_rate=0.1; total time=   9.1s
[CV] END depth=6, iterations=500, l2_leaf_reg=7, learning_rate=0.03; total time=   7.8s
[CV] END depth=6, iterations=500, l2_leaf_reg=7, learning_rate=0.03; total time=   7.4s
[CV] END depth=6, iterations=500, l2_leaf_reg=7, learning_rate=0.03; total time=   8.3s
[CV] END depth=6, iterations=500, l2_leaf_reg=7, learning_rate=0.05; total time=   7.8s
[CV] END depth=6, iterations=500, l2_leaf_reg=7, learning_rate=0.05; total time=   9.8s
[CV] END depth=6, iterations=500, l2_leaf_reg=7, learning_rate=0.05; total time=   6.9s
[CV] END depth=6, iterations=500, l2_leaf_reg=7, learning_rate=0.1; total time=   7.8s
[CV] END depth=6, iterations=500, l2_leaf_reg=7, learning_rate=0.1; total time=   9.3s
[CV] END depth=6, iterations=500, l2_leaf_reg=7, learning_rate=0.1; total time=   8.0s
[CV] END depth=6, iterations=1000, l2_leaf_reg=3, learning_rate=0.03; total time=  17.0s
[CV] END depth=6, iterations=1000, l2_leaf_reg=3, learning_rate=0.03; total time=  15.4s
[CV] END depth=6, iterations=1000, l2_leaf_reg=3, learning_rate=0.03; total time=  17.0s
[CV] END depth=6, iterations=1000, l2_leaf_reg=3, learning_rate=0.05; total time=  17.8s
[CV] END depth=6, iterations=1000, l2_leaf_reg=3, learning_rate=0.05; total time=  15.9s
[CV] END depth=6, iterations=1000, l2_leaf_reg=3, learning_rate=0.05; total time=  15.3s
[CV] END depth=6, iterations=1000, l2_leaf_reg=3, learning_rate=0.1; total time=  17.9s
[CV] END depth=6, iterations=1000, l2_leaf_reg=3, learning_rate=0.1; total time=  16.1s
[CV] END depth=6, iterations=1000, l2_leaf_reg=3, learning_rate=0.1; total time=  16.5s
[CV] END depth=6, iterations=1000, l2_leaf_reg=5, learning_rate=0.03; total time=  16.0s
[CV] END depth=6, iterations=1000, l2_leaf_reg=5, learning_rate=0.03; total time=  15.1s
[CV] END depth=6, iterations=1000, l2_leaf_reg=5, learning_rate=0.03; total time=  17.6s
[CV] END depth=6, iterations=1000, l2_leaf_reg=5, learning_rate=0.05; total time=  16.1s
[CV] END depth=6, iterations=1000, l2_leaf_reg=5, learning_rate=0.05; total time=  17.4s
[CV] END depth=6, iterations=1000, l2_leaf_reg=5, learning_rate=0.05; total time=  15.3s
[CV] END depth=6, iterations=1000, l2_leaf_reg=5, learning_rate=0.1; total time=  18.7s
[CV] END depth=6, iterations=1000, l2_leaf_reg=5, learning_rate=0.1; total time=  17.9s
[CV] END depth=6, iterations=1000, l2_leaf_reg=5, learning_rate=0.1; total time=  16.2s
[CV] END depth=6, iterations=1000, l2_leaf_reg=7, learning_rate=0.03; total time=  16.8s
[CV] END depth=6, iterations=1000, l2_leaf_reg=7, learning_rate=0.03; total time=  15.7s
[CV] END depth=6, iterations=1000, l2_leaf_reg=7, learning_rate=0.03; total time=  15.1s
[CV] END depth=6, iterations=1000, l2_leaf_reg=7, learning_rate=0.05; total time=  17.9s
[CV] END depth=6, iterations=1000, l2_leaf_reg=7, learning_rate=0.05; total time=  16.8s
[CV] END depth=6, iterations=1000, l2_leaf_reg=7, learning_rate=0.05; total time=  15.8s
[CV] END depth=6, iterations=1000, l2_leaf_reg=7, learning_rate=0.1; total time=  17.7s
[CV] END depth=6, iterations=1000, l2_leaf_reg=7, learning_rate=0.1; total time=  18.0s
[CV] END depth=6, iterations=1000, l2_leaf_reg=7, learning_rate=0.1; total time=  18.4s
[CV] END depth=8, iterations=500, l2_leaf_reg=3, learning_rate=0.03; total time=  29.4s
[CV] END depth=8, iterations=500, l2_leaf_reg=3, learning_rate=0.03; total time=  26.3s

/home/kali/Documents/Diploma/hh-helper/.venv/lib/python3.13/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

[CV] END depth=8, iterations=500, l2_leaf_reg=3, learning_rate=0.03; total time=  25.7s
[CV] END depth=8, iterations=500, l2_leaf_reg=3, learning_rate=0.05; total time=  29.5s
[CV] END depth=8, iterations=500, l2_leaf_reg=3, learning_rate=0.05; total time=  23.0s
[CV] END depth=8, iterations=500, l2_leaf_reg=3, learning_rate=0.1; total time=  26.4s
[CV] END depth=8, iterations=500, l2_leaf_reg=3, learning_rate=0.05; total time=  23.3s
[CV] END depth=8, iterations=500, l2_leaf_reg=3, learning_rate=0.1; total time=  26.3s
[CV] END depth=8, iterations=500, l2_leaf_reg=3, learning_rate=0.1; total time=  23.4s
[CV] END depth=8, iterations=500, l2_leaf_reg=5, learning_rate=0.03; total time=  24.2s
[CV] END depth=8, iterations=500, l2_leaf_reg=5, learning_rate=0.03; total time=  29.3s
[CV] END depth=8, iterations=500, l2_leaf_reg=5, learning_rate=0.03; total time=  24.7s
[CV] END depth=8, iterations=500, l2_leaf_reg=5, learning_rate=0.05; total time=  26.4s
[CV] END depth=8, iterations=500, l2_leaf_reg=5, learning_rate=0.05; total time=  23.1s
[CV] END depth=8, iterations=500, l2_leaf_reg=5, learning_rate=0.05; total time=  23.7s
[CV] END depth=8, iterations=500, l2_leaf_reg=5, learning_rate=0.1; total time=  26.2s
[CV] END depth=8, iterations=500, l2_leaf_reg=5, learning_rate=0.1; total time=  30.4s
[CV] END depth=8, iterations=500, l2_leaf_reg=5, learning_rate=0.1; total time=  26.5s
[CV] END depth=8, iterations=500, l2_leaf_reg=7, learning_rate=0.03; total time=  23.1s
[CV] END depth=8, iterations=500, l2_leaf_reg=7, learning_rate=0.03; total time=  22.1s
[CV] END depth=8, iterations=500, l2_leaf_reg=7, learning_rate=0.03; total time=  24.0s
[CV] END depth=8, iterations=500, l2_leaf_reg=7, learning_rate=0.05; total time=  24.1s
[CV] END depth=8, iterations=500, l2_leaf_reg=7, learning_rate=0.05; total time=  23.7s
[CV] END depth=8, iterations=500, l2_leaf_reg=7, learning_rate=0.05; total time=  22.6s
[CV] END depth=8, iterations=500, l2_leaf_reg=7, learning_rate=0.1; total time=  25.7s
[CV] END depth=8, iterations=500, l2_leaf_reg=7, learning_rate=0.1; total time=  24.7s
[CV] END depth=8, iterations=500, l2_leaf_reg=7, learning_rate=0.1; total time=  25.7s
[CV] END depth=8, iterations=1000, l2_leaf_reg=3, learning_rate=0.03; total time=  53.3s
[CV] END depth=8, iterations=1000, l2_leaf_reg=3, learning_rate=0.03; total time=  49.5s
[CV] END depth=8, iterations=1000, l2_leaf_reg=3, learning_rate=0.03; total time=  50.4s
[CV] END depth=8, iterations=1000, l2_leaf_reg=3, learning_rate=0.05; total time=  57.3s
[CV] END depth=8, iterations=1000, l2_leaf_reg=3, learning_rate=0.05; total time=  54.2s
[CV] END depth=8, iterations=1000, l2_leaf_reg=3, learning_rate=0.05; total time=  51.5s
[CV] END depth=8, iterations=1000, l2_leaf_reg=3, learning_rate=0.1; total time=  54.2s
[CV] END depth=8, iterations=1000, l2_leaf_reg=3, learning_rate=0.1; total time=  52.5s
[CV] END depth=8, iterations=1000, l2_leaf_reg=3, learning_rate=0.1; total time=  54.4s
[CV] END depth=8, iterations=1000, l2_leaf_reg=5, learning_rate=0.03; total time=  50.2s
[CV] END depth=8, iterations=1000, l2_leaf_reg=5, learning_rate=0.03; total time=  52.7s
[CV] END depth=8, iterations=1000, l2_leaf_reg=5, learning_rate=0.03; total time=  46.9s
[CV] END depth=8, iterations=1000, l2_leaf_reg=5, learning_rate=0.05; total time=  57.2s
[CV] END depth=8, iterations=1000, l2_leaf_reg=5, learning_rate=0.05; total time=  54.2s
[CV] END depth=8, iterations=1000, l2_leaf_reg=5, learning_rate=0.05; total time=  48.1s
[CV] END depth=8, iterations=1000, l2_leaf_reg=5, learning_rate=0.1; total time=  55.3s
[CV] END depth=8, iterations=1000, l2_leaf_reg=5, learning_rate=0.1; total time=  58.9s
[CV] END depth=8, iterations=1000, l2_leaf_reg=5, learning_rate=0.1; total time=  57.0s
[CV] END depth=8, iterations=1000, l2_leaf_reg=7, learning_rate=0.03; total time= 1.0min
[CV] END depth=8, iterations=1000, l2_leaf_reg=7, learning_rate=0.03; total time=  54.9s
[CV] END depth=8, iterations=1000, l2_leaf_reg=7, learning_rate=0.03; total time= 1.0min
[CV] END depth=8, iterations=1000, l2_leaf_reg=7, learning_rate=0.05; total time= 1.3min
[CV] END depth=8, iterations=1000, l2_leaf_reg=7, learning_rate=0.05; total time= 1.1min
[CV] END depth=8, iterations=1000, l2_leaf_reg=7, learning_rate=0.05; total time= 1.2min
[CV] END depth=8, iterations=1000, l2_leaf_reg=7, learning_rate=0.1; total time=  58.7s
[CV] END depth=8, iterations=1000, l2_leaf_reg=7, learning_rate=0.1; total time=  46.8s
[CV] END depth=8, iterations=1000, l2_leaf_reg=7, learning_rate=0.1; total time=  48.0s
Лучшие параметры: {'depth': 6, 'iterations': 1000, 'l2_leaf_reg': 3, 'learning_rate': 0.05}
Лучший CV score: 0.26317317415309316

In [36]:
best_model = grid.best_estimator_

best_model.fit(
    train_pool,
    eval_set=valid_pool,
    use_best_model=True
)

CatBoostRegressor(depth=6, eval_metric='MAE', iterations=1000, l2_leaf_reg=3, learning_rate=0.05, loss_function='RMSE', od_type='Iter', od_wait=100, random_seed=42, verbose=0)

In [37]:
# =========================================================
# 9. Оценка качества
# =========================================================
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

pred_valid_log = best_model.predict(X_valid)
pred_valid = np.expm1(pred_valid_log)
true_valid = np.expm1(y_valid.values)

mae = mean_absolute_error(true_valid, pred_valid)
mse = mean_squared_error(true_valid, pred_valid)
r2 = r2_score(true_valid, pred_valid)

try:
    from sklearn.metrics import root_mean_squared_error
    rmse = root_mean_squared_error(true_valid, pred_valid)
except ImportError:
    rmse = np.sqrt(mean_squared_error(true_valid, pred_valid))

print(f"Validation MAE:  {mae:,.2f} RUB")
print(f"Validation RMSE: {rmse:,.2f} RUB")
print(f"Validation MSE:  {mse:,.2f}")
print(f"Validation R2:   {r2:.4f}")

Validation MAE:  45,299.31 RUB
Validation RMSE: 62,745.12 RUB
Validation MSE:  3,936,950,425.13
Validation R2:   0.7057

In [27]:
# =========================================================
# 8. Обучение CatBoost
# =========================================================
model = CatBoostRegressor(
    loss_function="RMSE",
    eval_metric="MAE",
    iterations=2000,
    learning_rate=0.03,
    depth=6,
    l2_leaf_reg=5,
    random_strength=1,
    bagging_temperature=1,
    od_type="Iter",
    od_wait=100,
    random_seed=42,
    verbose=100
)

model.fit(
    train_pool,
    eval_set=valid_pool,
    use_best_model=True
)

0:	learn: 0.4573613	test: 0.4703267	best: 0.4703267 (0)	total: 7.4ms	remaining: 14.8s
100:	learn: 0.2775572	test: 0.2907656	best: 0.2907656 (100)	total: 749ms	remaining: 14.1s
200:	learn: 0.2345196	test: 0.2532077	best: 0.2530853 (198)	total: 1.35s	remaining: 12.1s
300:	learn: 0.2049866	test: 0.2382625	best: 0.2382625 (300)	total: 1.95s	remaining: 11s
400:	learn: 0.1840527	test: 0.2316902	best: 0.2316902 (400)	total: 2.54s	remaining: 10.1s
500:	learn: 0.1652693	test: 0.2273069	best: 0.2273069 (500)	total: 3.13s	remaining: 9.37s
600:	learn: 0.1511587	test: 0.2268803	best: 0.2266695 (581)	total: 3.75s	remaining: 8.73s
700:	learn: 0.1382397	test: 0.2266824	best: 0.2261861 (640)	total: 4.35s	remaining: 8.05s
800:	learn: 0.1290879	test: 0.2266999	best: 0.2258799 (732)	total: 4.9s	remaining: 7.34s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.2258799219
bestIteration = 732

Shrink model to first 733 iterations.

CatBoostRegressor(bagging_temperature=1, depth=6, eval_metric='MAE', iterations=2000, l2_leaf_reg=5, learning_rate=0.03, loss_function='RMSE', od_type='Iter', od_wait=100, random_seed=42, random_strength=1, verbose=100)

In [30]:
# =========================================================
# 9. Оценка качества
# =========================================================
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

pred_valid_log = model.predict(X_valid)
pred_valid = np.expm1(pred_valid_log)
true_valid = np.expm1(y_valid.values)

mae = mean_absolute_error(true_valid, pred_valid)
mse = mean_squared_error(true_valid, pred_valid)
r2 = r2_score(true_valid, pred_valid)

try:
    from sklearn.metrics import root_mean_squared_error
    rmse = root_mean_squared_error(true_valid, pred_valid)
except ImportError:
    rmse = np.sqrt(mean_squared_error(true_valid, pred_valid))

print(f"Validation MAE:  {mae:,.2f} RUB")
print(f"Validation RMSE: {rmse:,.2f} RUB")
print(f"Validation MSE:  {mse:,.2f}")
print(f"Validation R2:   {r2:.4f}")

Validation MAE:  46,190.28 RUB
Validation RMSE: 63,907.49 RUB
Validation MSE:  4,084,167,911.73
Validation R2:   0.6947

In [29]:
# =========================================================
# 10. Важность признаков
# =========================================================
feature_importance = pd.DataFrame({
    "feature": feature_cols,
    "importance": model.get_feature_importance(train_pool)
}).sort_values("importance", ascending=False)

print(feature_importance)

                    feature  importance
3           experience_name   40.215735
0                      name   23.793407
6               work_format    6.546052
1        professional_roles    6.461620
2                 area_name    6.164525
5           employment_name    5.065763
4             schedule_name    2.715333
9                 skill_SQL    1.937753
7                internship    1.346616
17                 skill_ML    1.107066
8              skill_Python    1.010514
13              skill_Linux    0.536868
25             skill_pandas    0.492792
37                skill_API    0.376182
12            skill_PyTorch    0.349507
32         skill_Clickhouse    0.291696
36              skill_Numpy    0.241212
19             skill_MLflow    0.225267
28  skill_Машинное обучение    0.211511
27                skill_NLP    0.150097
30      skill_Deep Learning    0.134693
22    skill_Английский язык    0.110717
29       skill_Apache Kafka    0.091218
16                skill_Git    0.083483
34      skill_Анализ данных    0.064627
35              skill_Redis    0.060930
11         skill_PostgreSQL    0.049470
21              skill_CI/CD    0.034682
18            skill_FastAPI    0.026842
14                skill_LLM    0.026836
23           skill_Big Data    0.022463
15         skill_Kubernetes    0.017894
20         skill_TensorFlow    0.016939
24     skill_Apache Airflow    0.011598
33                 skill_AI    0.004108
10             skill_Docker    0.003982
31            skill_Grafana    0.000000
26           skill_REST API    0.000000

In [23]:
# =========================================================
# 11. Предсказания для всего датасета
# =========================================================
full_df = df.copy()

for col in text_cols:
    full_df[col] = full_df[col].fillna("").astype(str)

for col in cat_cols:
    full_df[col] = full_df[col].fillna("UNKNOWN").astype(str)

full_df["internship"] = full_df["internship"].astype(int)
full_df["published_at"] = pd.to_datetime(full_df["published_at"], errors="coerce")
full_df["pub_year"] = full_df["published_at"].dt.year.fillna(0).astype(int)
full_df["pub_month"] = full_df["published_at"].dt.month.fillna(0).astype(int)
full_df["pub_weekday"] = full_df["published_at"].dt.weekday.fillna(0).astype(int)

X_all = full_df[feature_cols].copy()

pred_all_log = model.predict(X_all)
full_df["pred_salary_rub"] = np.expm1(pred_all_log)

# Подрезка слишком странных значений
full_df["pred_salary_rub"] = full_df["pred_salary_rub"].clip(20000, 1000000)

print(full_df[[
    "name",
    "area_name",
    "experience_name",
    "target_salary",
    "pred_salary_rub"
]].head())

                                                name area_name  \
0             ML-инженер / Machine Learning Engineer    Алматы
1  Инженер компьютерного зрения / Machine Learnin...   Воронеж
2          Machine Learning Engineer (RecSys, E-com)    Москва
3                     AI / Machine Learning Engineer   Ташкент
4                         Robotics Software Engineer    Москва

      experience_name  target_salary  pred_salary_rub
0       От 3 до 6 лет       202568.4    200842.112998
1  От 1 года до 3 лет       150000.0    149937.026325
2  От 1 года до 3 лет            NaN    169744.911109
3       От 3 до 6 лет        98264.1    102031.580256
4  От 1 года до 3 лет            NaN    139711.390330

In [24]:
# =========================================================
# 12. Сохранение результатов
# =========================================================
result_cols = [
    "vacancy_id",
    "name",
    "area_name",
    "experience_name",
    "employment_name",
    "schedule_name",
    "work_format",
    "employer_name",
    "target_salary",
    "pred_salary_rub"
]

available_result_cols = [c for c in result_cols if c in full_df.columns]
predictions_df = full_df[available_result_cols].copy()

predictions_df.to_csv("vacancy_salary_predictions_catboost.csv", index=False)
print("Файл сохранён: vacancy_salary_predictions_catboost.csv")

Файл сохранён: vacancy_salary_predictions_catboost.csv